const actions = {
  GET_SAVED_DATA: 'GET_SAVED_DATA',
  UPDATE_SAVED_DATA: 'UPDATE_SAVED_DATA',
  DELETE_SAVED_DATA: 'DELETE_SAVED_DATA',
  POST_INPUT_DATA: 'POST_INPUT_DATA',
  FETCH_PREDICTION_SUCCESS: 'GOT_PREDICTION_SUCCESS',
  FETCH_PREDICTION_FALIURE: 'GOT_PREDICTION_FALIURE',
  FETCH_PREDICTION_LOADING: 'GOT_PREDICTION_LOADING',
};

export default Actions = {...Object.freeze(actions)};
